Repository aws/sagemaker-xgboost-container, pull requests merged in 2022-09, with the labels that each got.

#322 Maintain the order of union metric list in distributed training
  src/sagemaker_xgboost_container/algorithm_mode/train_utils.py
  src/sagemaker_xgboost_container/metrics/custom_metrics.py
  test/unit/algorithm_mode/test_custom_metrics.py
Labels: bug, 1.2-2

#321 Maintain the order of union metric list in distributed training
  src/sagemaker_xgboost_container/algorithm_mode/train_utils.py
Labels: bug, 1.5-1

#323 Maintain the order of union metric list in distributed training
  src/sagemaker_xgboost_container/algorithm_mode/train_utils.py
  src/sagemaker_xgboost_container/metrics/custom_metrics.py
  test/unit/algorithm_mode/test_custom_metrics.py
Labels: bug, 1.2-1

#326 Add testing section to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1.5-1
